import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/Header/Header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body>
        <div className="flex h-screen oveflow">
			<div className="flex flex-col flex-1 oveflow-auto">
				<div className="max-w-7xl mx-auto w-full">
					<Header />
          <main>{children}</main>
				</div>

			</div>
      
		</div>
 
        
      </body>
      {/* <main>{children}</main> */}
    </html>
  );
}
